BTC_Simulate.exe listAddresses

BTC_Simulate.exe transfer 1JbPyoZNo4gqtjrv2PuDdiEJMCvs2MVqfa 1Nqw3P1pYH1vhuwsktProgXeEqgpUzChyo 1.25 144xAeAczrjtukaoL1ppDsekfNemNeAhqt "I am mogul"

BTC_Simulate.exe getBalance --address 144xAeAczrjtukaoL1ppDsekfNemNeAhqt
BTC_Simulate.exe getBalance --address 1JbPyoZNo4gqtjrv2PuDdiEJMCvs2MVqfa
BTC_Simulate.exe getBalance --address 1Nqw3P1pYH1vhuwsktProgXeEqgpUzChyo

BTC_Simulate.exe printBlockchain
